swagger: '2.0'
info:
  description: 'This is a sample server Petstore server.  You can find out more about     Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).      For this sample, you can use the api key `special-key` to test the authorization     filters.'
  version: 1.0.0
  title: Swagger Petstore
  termsOfService: 'http://swagger.io/terms/'
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: 'localhost:4011'
tags: []
schemes:
  - http
paths:
  /challengethemes:
    post:
      summary: Add a new challenge theme
      description: チャレンジネタ新規作成
      operationId: ''
      consumes:
        - multipart/form-data
      produces:
        - application/json
      parameters:
        - in: formData
          type: file
          name: content
          description: image or video
          required: true
        - in: formData
          type: string
          name: theme_data
          description: JSON
          required: true
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/challenge-theme'
          examples:
            example-1:
              id: 2
              title: トイレットペーパーリフティング
              description: １０秒間でトイレットペーパーを使用して何回リフティングできるか競おう！
              user:
                id: 3
                name: ロナウド
              recordable: true
              is_int: true
              unit: 回
              ranking_type: DESC
              created_at: '2020-05-03 16:04:35'
        '400':
          description: Bad Request
          schema: {}
        '403':
          description: Forbidden
          schema: {}
      security:
        - Authorization: []
    parameters: []
    get:
      summary: ''
      operationId: get-challengethemes
      produces:
        - application/json
      responses:
        '200':
          description: チャレンジネタのリスト
          schema:
            type: array
            items:
              $ref: '#/definitions/challenge-theme'
          examples:
            example-1:
              - id: 2
                title: トイレットペーパーリフティング
                description: １０秒間でトイレットペーパーを使用して何回リフティングできるか競おう！
                user:
                  id: 3
                  name: ロナウド
                recordable: true
                is_int: true
                unit: 回
                ranking_type: DESC
                created_at: '2020-05-03 16:04:35'
        '400':
          description: Bad Request
          schema: {}
      description: ''
      parameters:
        - type: boolean
          in: query
          name: recordable
  /users/login:
    parameters: []
    get:
      summary: ''
      operationId: get-users-login
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/user'
          examples:
            example-1:
              id: 4
              name: メッシ
        '400':
          description: Bad Request
          schema: {}
        '401':
          description: Unauthorized
          schema: {}
      security:
        - Authorization: []
  '/challengethemes/{challenge_theme_id}':
    parameters:
      - type: string
        name: challenge_theme_id
        in: path
        required: true
    get:
      summary: ''
      tags: []
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/challenge-theme'
          examples:
            example-1:
              id: 2
              title: トイレットペーパーリフティング
              description: １０秒間でトイレットペーパーを使用して何回リフティングできるか競おう！
              user:
                id: 3
                name: ロナウド
              recordable: true
              is_int: true
              unit: 回
              ranking_type: DESC
              created_at: '2020-05-03 16:04:35'
        '404':
          description: Not Found
          schema: {}
      operationId: get-challengetheme-challenge_theme_id
  /challengerecords:
    parameters: []
    get:
      summary: ''
      operationId: get-challengerecords
      responses:
        '200':
          description: ''
          schema:
            type: array
            items:
              $ref: '#/definitions/challenge-record'
          examples:
            example-1:
              - id: 1
                content: url
                comment: 挑戦してみました！
                challenge_theme:
                  id: 2
                  title: トイレットペーパーリフティング
                  description: １０秒間でトイレットペーパーを使用して何回リフティングできるか競おう！
                  user:
                    id: 3
                    name: ロナウド
                  recordable: true
                  is_int: true
                  unit: 回
                  ranking_type: DESC
                  created_at: '2020-05-03 16:04:35'
                user:
                  id: 4
                  name: メッシ
                record: 30
                created_at: '2020-05-03 16:06:52'
        '400':
          description: Bad Request
          schema: {}
      parameters:
        - type: boolean
          in: query
          name: recordable
      description: created_atが新しい順でチャレンジレコードのリストを取得
    post:
      summary: ''
      operationId: post-challengerecords
      consumes:
        - multipart/form-data
      produces:
        - application/json
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/challenge-record'
          examples:
            example-1:
              id: 1
              content: url
              comment: 挑戦してみました！
              challenge_theme:
                id: 2
                title: トイレットペーパーリフティング
                description: １０秒間でトイレットペーパーを使用して何回リフティングできるか競おう！
                user:
                  id: 3
                  name: ロナウド
                recordable: true
                is_int: true
                unit: 回
                ranking_type: DESC
                created_at: '2020-05-03 16:04:35'
              user:
                id: 4
                name: メッシ
              record: 30
              created_at: '2020-05-03 16:06:52'
        '400':
          description: Bad Request
          schema: {}
        '403':
          description: Forbidden
          schema: {}
      parameters:
        - in: formData
          type: file
          name: content
          description: image or movie
          required: true
        - in: formData
          type: string
          name: record_data
          description: JSON
          required: true
      security:
        - Authorization: []
  '/challengethemes/{challenge_theme_id}/challengerecords':
    parameters:
      - type: string
        name: challenge_theme_id
        in: path
        required: true
    get:
      summary: ''
      tags: []
      responses:
        '200':
          description: ''
          schema:
            type: array
            items:
              $ref: '#/definitions/challenge-record'
          examples:
            example-1:
              - id: 1
                content: url
                comment: 挑戦してみました！
                challenge_theme:
                  id: 2
                  title: トイレットペーパーリフティング
                  description: １０秒間でトイレットペーパーを使用して何回リフティングできるか競おう！
                  user:
                    id: 3
                    name: ロナウド
                  recordable: true
                  is_int: true
                  unit: 回
                  ranking_type: DESC
                  created_at: '2020-05-03 16:04:35'
                user:
                  id: 4
                  name: メッシ
                record: 30
                created_at: '2020-05-03 16:06:52'
        '400':
          description: Bad Request
          schema: {}
        '404':
          description: Not Found
          schema: {}
      operationId: get-challengetheme-challenge_theme_id-challengerecord
      parameters:
        - type: string
          in: query
          name: sort
  '/users/{user_id}/challengethemes':
    parameters:
      - type: string
        name: user_id
        in: path
        required: true
    get:
      summary: ''
      tags: []
      responses:
        '200':
          description: チャレンジネタのリスト
          schema:
            type: array
            items:
              $ref: '#/definitions/challenge-theme'
          examples:
            example-1:
              - id: 2
                title: トイレットペーパーリフティング
                description: １０秒間でトイレットペーパーを使用して何回リフティングできるか競おう！
                user:
                  id: 3
                  name: ロナウド
                recordable: true
                is_int: true
                unit: 回
                ranking_type: DESC
                created_at: '2020-05-03 16:04:35'
        '400':
          description: Bad Request
          schema: {}
        '404':
          description: Not Found
          schema: {}
      operationId: get-users-user_id-challengethemes
      parameters:
        - type: boolean
          in: query
          name: recordable
      description: ''
  '/users/{user_id}/challengerecords':
    parameters:
      - type: string
        name: user_id
        in: path
        required: true
    get:
      summary: ''
      tags: []
      responses:
        '200':
          description: ''
          schema:
            type: array
            items:
              $ref: '#/definitions/challenge-record'
          examples:
            example-1:
              - id: 1
                content: url
                comment: 挑戦してみました！
                challenge_theme:
                  id: 2
                  title: トイレットペーパーリフティング
                  description: １０秒間でトイレットペーパーを使用して何回リフティングできるか競おう！
                  user:
                    id: 3
                    name: ロナウド
                  recordable: true
                  is_int: true
                  unit: 回
                  ranking_type: DESC
                  created_at: '2020-05-03 16:04:35'
                user:
                  id: 4
                  name: メッシ
                record: 30
                created_at: '2020-05-03 16:06:52'
        '400':
          description: Bad Request
          schema: {}
        '404':
          description: Not Found
          schema: {}
      operationId: get-users-user_id-challengerecords
      parameters:
        - type: boolean
          in: query
          name: recordable
  /users:
    post:
      summary: ''
      operationId: post-users
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/user'
          headers: {}
          examples:
            example-1:
              id: 4
              name: メッシ
        '400':
          description: Bad Request
          schema: {}
        '401':
          description: Unauthorized
          schema: {}
      parameters:
        - in: body
          name: body
          schema:
            type: object
            properties:
              name:
                type: string
            required:
              - name
      security:
        - Authorization: []
  '/users/{user_id}':
    parameters:
      - type: string
        name: user_id
        in: path
        required: true
    get:
      summary: ''
      tags: []
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/user'
          examples:
            example-1:
              id: 4
              name: メッシ
        '404':
          description: Not Found
          schema: {}
      operationId: get-users-user_id
securityDefinitions:
  Authorization:
    name: X-JWT-TOKEN
    type: apiKey
    in: header
definitions:
  challenge-theme:
    title: challenge-theme
    type: object
    description: ''
    properties:
      id:
        type: integer
      title:
        type: string
      description:
        type: string
      user:
        $ref: '#/definitions/user'
      recordable:
        type: boolean
      is_int:
        type: 'boolean'
      unit:
        type: string
      ranking_type:
        type: string
        enum:
          - ASC
          - DESC
          - FAV
      created_at:
        type: string
        format: date-time
    required:
      - id
      - title
      - description
      - user
      - recordable
      - is_int
      - unit
      - ranking_type
      - created_at
    x-examples:
      example-1:
        id: 2
        title: トイレットペーパーリフティング
        description: １０秒間でトイレットペーパーを使用して何回リフティングできるか競おう！
        user:
          id: 3
          name: ロナウド
        recordable: true
        is_int: true
        unit: 回
        ranking_type: DESC
        created_at: '2020-05-03 16:04:35'
  user:
    title: user
    type: object
    description: ''
    properties:
      id:
        type: integer
      name:
        type: string
    required:
      - id
      - name
    x-examples:
      example-1:
        id: 4
        name: メッシ
  challenge-record:
    title: challenge-record
    type: object
    description: ''
    properties:
      id:
        type: integer
      content:
        type: string
        format: uri
      comment:
        type: string
      challenge_theme:
        $ref: '#/definitions/challenge-theme'
      user:
        $ref: '#/definitions/user'
      record:
        type: number
      created_at:
        type: string
        format: date-time
    required:
      - id
      - content
      - comment
      - challenge_theme
      - user
      - record
      - created_at
    x-examples:
      example-1:
        id: 1
        content: url
        comment: 挑戦してみました！
        challenge_theme:
          id: 2
          title: トイレットペーパーリフティング
          description: １０秒間でトイレットペーパーを使用して何回リフティングできるか競おう！
          user:
            id: 3
            name: ロナウド
          recordable: true
          is_int: true
          unit: 回
          ranking_type: DESC
          created_at: '2020-05-03 16:04:35'
        user:
          id: 4
          name: メッシ
        record: 30
        created_at: '2020-05-03 16:06:52'
  tag:
    title: tag
    type: object
    properties:
      id:
        type: integer
      text:
        type: string
    required:
      - id
      - text
externalDocs:
  description: Find out more about Swagger
  url: 'http://swagger.io'