// Code generated by SQLBoiler 3.6.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package model

var TableNames = struct {
	ChallengeRecords  string
	ChallengeThemes   string
	Favorites         string
	Tags              string
	ThemeTagRelations string
	Users             string
}{
	ChallengeRecords:  "challenge_records",
	ChallengeThemes:   "challenge_themes",
	Favorites:         "favorites",
	Tags:              "tags",
	ThemeTagRelations: "theme_tag_relations",
	Users:             "users",
}
