// Code generated by SQLBoiler 4.0.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package model

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testChallengeThemes(t *testing.T) {
	t.Parallel()

	query := ChallengeThemes()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testChallengeThemesDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ChallengeTheme{}
	if err = randomize.Struct(seed, o, challengeThemeDBTypes, true, challengeThemeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ChallengeTheme struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := ChallengeThemes().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testChallengeThemesQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ChallengeTheme{}
	if err = randomize.Struct(seed, o, challengeThemeDBTypes, true, challengeThemeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ChallengeTheme struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := ChallengeThemes().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := ChallengeThemes().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testChallengeThemesSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ChallengeTheme{}
	if err = randomize.Struct(seed, o, challengeThemeDBTypes, true, challengeThemeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ChallengeTheme struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := ChallengeThemeSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := ChallengeThemes().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testChallengeThemesExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ChallengeTheme{}
	if err = randomize.Struct(seed, o, challengeThemeDBTypes, true, challengeThemeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ChallengeTheme struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := ChallengeThemeExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if ChallengeTheme exists: %s", err)
	}
	if !e {
		t.Errorf("Expected ChallengeThemeExists to return true, but got false.")
	}
}

func testChallengeThemesFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ChallengeTheme{}
	if err = randomize.Struct(seed, o, challengeThemeDBTypes, true, challengeThemeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ChallengeTheme struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	challengeThemeFound, err := FindChallengeTheme(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if challengeThemeFound == nil {
		t.Error("want a record, got nil")
	}
}

func testChallengeThemesBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ChallengeTheme{}
	if err = randomize.Struct(seed, o, challengeThemeDBTypes, true, challengeThemeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ChallengeTheme struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = ChallengeThemes().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testChallengeThemesOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ChallengeTheme{}
	if err = randomize.Struct(seed, o, challengeThemeDBTypes, true, challengeThemeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ChallengeTheme struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := ChallengeThemes().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testChallengeThemesAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	challengeThemeOne := &ChallengeTheme{}
	challengeThemeTwo := &ChallengeTheme{}
	if err = randomize.Struct(seed, challengeThemeOne, challengeThemeDBTypes, false, challengeThemeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ChallengeTheme struct: %s", err)
	}
	if err = randomize.Struct(seed, challengeThemeTwo, challengeThemeDBTypes, false, challengeThemeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ChallengeTheme struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = challengeThemeOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = challengeThemeTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := ChallengeThemes().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testChallengeThemesCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	challengeThemeOne := &ChallengeTheme{}
	challengeThemeTwo := &ChallengeTheme{}
	if err = randomize.Struct(seed, challengeThemeOne, challengeThemeDBTypes, false, challengeThemeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ChallengeTheme struct: %s", err)
	}
	if err = randomize.Struct(seed, challengeThemeTwo, challengeThemeDBTypes, false, challengeThemeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ChallengeTheme struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = challengeThemeOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = challengeThemeTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := ChallengeThemes().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func challengeThemeBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *ChallengeTheme) error {
	*o = ChallengeTheme{}
	return nil
}

func challengeThemeAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *ChallengeTheme) error {
	*o = ChallengeTheme{}
	return nil
}

func challengeThemeAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *ChallengeTheme) error {
	*o = ChallengeTheme{}
	return nil
}

func challengeThemeBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *ChallengeTheme) error {
	*o = ChallengeTheme{}
	return nil
}

func challengeThemeAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *ChallengeTheme) error {
	*o = ChallengeTheme{}
	return nil
}

func challengeThemeBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *ChallengeTheme) error {
	*o = ChallengeTheme{}
	return nil
}

func challengeThemeAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *ChallengeTheme) error {
	*o = ChallengeTheme{}
	return nil
}

func challengeThemeBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *ChallengeTheme) error {
	*o = ChallengeTheme{}
	return nil
}

func challengeThemeAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *ChallengeTheme) error {
	*o = ChallengeTheme{}
	return nil
}

func testChallengeThemesHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &ChallengeTheme{}
	o := &ChallengeTheme{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, challengeThemeDBTypes, false); err != nil {
		t.Errorf("Unable to randomize ChallengeTheme object: %s", err)
	}

	AddChallengeThemeHook(boil.BeforeInsertHook, challengeThemeBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	challengeThemeBeforeInsertHooks = []ChallengeThemeHook{}

	AddChallengeThemeHook(boil.AfterInsertHook, challengeThemeAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	challengeThemeAfterInsertHooks = []ChallengeThemeHook{}

	AddChallengeThemeHook(boil.AfterSelectHook, challengeThemeAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	challengeThemeAfterSelectHooks = []ChallengeThemeHook{}

	AddChallengeThemeHook(boil.BeforeUpdateHook, challengeThemeBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	challengeThemeBeforeUpdateHooks = []ChallengeThemeHook{}

	AddChallengeThemeHook(boil.AfterUpdateHook, challengeThemeAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	challengeThemeAfterUpdateHooks = []ChallengeThemeHook{}

	AddChallengeThemeHook(boil.BeforeDeleteHook, challengeThemeBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	challengeThemeBeforeDeleteHooks = []ChallengeThemeHook{}

	AddChallengeThemeHook(boil.AfterDeleteHook, challengeThemeAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	challengeThemeAfterDeleteHooks = []ChallengeThemeHook{}

	AddChallengeThemeHook(boil.BeforeUpsertHook, challengeThemeBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	challengeThemeBeforeUpsertHooks = []ChallengeThemeHook{}

	AddChallengeThemeHook(boil.AfterUpsertHook, challengeThemeAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	challengeThemeAfterUpsertHooks = []ChallengeThemeHook{}
}

func testChallengeThemesInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ChallengeTheme{}
	if err = randomize.Struct(seed, o, challengeThemeDBTypes, true, challengeThemeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ChallengeTheme struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := ChallengeThemes().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testChallengeThemesInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ChallengeTheme{}
	if err = randomize.Struct(seed, o, challengeThemeDBTypes, true); err != nil {
		t.Errorf("Unable to randomize ChallengeTheme struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(challengeThemeColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := ChallengeThemes().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testChallengeThemeToManyChallengeRecords(t *testing.T) {
	var err error
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a ChallengeTheme
	var b, c ChallengeRecord

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, challengeThemeDBTypes, true, challengeThemeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ChallengeTheme struct: %s", err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = randomize.Struct(seed, &b, challengeRecordDBTypes, false, challengeRecordColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, challengeRecordDBTypes, false, challengeRecordColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}

	b.ChallengeThemeID = a.ID
	c.ChallengeThemeID = a.ID

	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := a.ChallengeRecords().All(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	bFound, cFound := false, false
	for _, v := range check {
		if v.ChallengeThemeID == b.ChallengeThemeID {
			bFound = true
		}
		if v.ChallengeThemeID == c.ChallengeThemeID {
			cFound = true
		}
	}

	if !bFound {
		t.Error("expected to find b")
	}
	if !cFound {
		t.Error("expected to find c")
	}

	slice := ChallengeThemeSlice{&a}
	if err = a.L.LoadChallengeRecords(ctx, tx, false, (*[]*ChallengeTheme)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.ChallengeRecords); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	a.R.ChallengeRecords = nil
	if err = a.L.LoadChallengeRecords(ctx, tx, true, &a, nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.ChallengeRecords); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	if t.Failed() {
		t.Logf("%#v", check)
	}
}

func testChallengeThemeToManyThemeTagRelations(t *testing.T) {
	var err error
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a ChallengeTheme
	var b, c ThemeTagRelation

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, challengeThemeDBTypes, true, challengeThemeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ChallengeTheme struct: %s", err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = randomize.Struct(seed, &b, themeTagRelationDBTypes, false, themeTagRelationColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, themeTagRelationDBTypes, false, themeTagRelationColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}

	b.ChallengeThemeID = a.ID
	c.ChallengeThemeID = a.ID

	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := a.ThemeTagRelations().All(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	bFound, cFound := false, false
	for _, v := range check {
		if v.ChallengeThemeID == b.ChallengeThemeID {
			bFound = true
		}
		if v.ChallengeThemeID == c.ChallengeThemeID {
			cFound = true
		}
	}

	if !bFound {
		t.Error("expected to find b")
	}
	if !cFound {
		t.Error("expected to find c")
	}

	slice := ChallengeThemeSlice{&a}
	if err = a.L.LoadThemeTagRelations(ctx, tx, false, (*[]*ChallengeTheme)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.ThemeTagRelations); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	a.R.ThemeTagRelations = nil
	if err = a.L.LoadThemeTagRelations(ctx, tx, true, &a, nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.ThemeTagRelations); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	if t.Failed() {
		t.Logf("%#v", check)
	}
}

func testChallengeThemeToManyAddOpChallengeRecords(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a ChallengeTheme
	var b, c, d, e ChallengeRecord

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, challengeThemeDBTypes, false, strmangle.SetComplement(challengeThemePrimaryKeyColumns, challengeThemeColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*ChallengeRecord{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, challengeRecordDBTypes, false, strmangle.SetComplement(challengeRecordPrimaryKeyColumns, challengeRecordColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	foreignersSplitByInsertion := [][]*ChallengeRecord{
		{&b, &c},
		{&d, &e},
	}

	for i, x := range foreignersSplitByInsertion {
		err = a.AddChallengeRecords(ctx, tx, i != 0, x...)
		if err != nil {
			t.Fatal(err)
		}

		first := x[0]
		second := x[1]

		if a.ID != first.ChallengeThemeID {
			t.Error("foreign key was wrong value", a.ID, first.ChallengeThemeID)
		}
		if a.ID != second.ChallengeThemeID {
			t.Error("foreign key was wrong value", a.ID, second.ChallengeThemeID)
		}

		if first.R.ChallengeTheme != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}
		if second.R.ChallengeTheme != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}

		if a.R.ChallengeRecords[i*2] != first {
			t.Error("relationship struct slice not set to correct value")
		}
		if a.R.ChallengeRecords[i*2+1] != second {
			t.Error("relationship struct slice not set to correct value")
		}

		count, err := a.ChallengeRecords().Count(ctx, tx)
		if err != nil {
			t.Fatal(err)
		}
		if want := int64((i + 1) * 2); count != want {
			t.Error("want", want, "got", count)
		}
	}
}
func testChallengeThemeToManyAddOpThemeTagRelations(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a ChallengeTheme
	var b, c, d, e ThemeTagRelation

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, challengeThemeDBTypes, false, strmangle.SetComplement(challengeThemePrimaryKeyColumns, challengeThemeColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*ThemeTagRelation{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, themeTagRelationDBTypes, false, strmangle.SetComplement(themeTagRelationPrimaryKeyColumns, themeTagRelationColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	foreignersSplitByInsertion := [][]*ThemeTagRelation{
		{&b, &c},
		{&d, &e},
	}

	for i, x := range foreignersSplitByInsertion {
		err = a.AddThemeTagRelations(ctx, tx, i != 0, x...)
		if err != nil {
			t.Fatal(err)
		}

		first := x[0]
		second := x[1]

		if a.ID != first.ChallengeThemeID {
			t.Error("foreign key was wrong value", a.ID, first.ChallengeThemeID)
		}
		if a.ID != second.ChallengeThemeID {
			t.Error("foreign key was wrong value", a.ID, second.ChallengeThemeID)
		}

		if first.R.ChallengeTheme != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}
		if second.R.ChallengeTheme != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}

		if a.R.ThemeTagRelations[i*2] != first {
			t.Error("relationship struct slice not set to correct value")
		}
		if a.R.ThemeTagRelations[i*2+1] != second {
			t.Error("relationship struct slice not set to correct value")
		}

		count, err := a.ThemeTagRelations().Count(ctx, tx)
		if err != nil {
			t.Fatal(err)
		}
		if want := int64((i + 1) * 2); count != want {
			t.Error("want", want, "got", count)
		}
	}
}
func testChallengeThemeToOneUserUsingUser(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local ChallengeTheme
	var foreign User

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, challengeThemeDBTypes, false, challengeThemeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ChallengeTheme struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, userDBTypes, false, userColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize User struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.UserID = foreign.ID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.User().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.ID != foreign.ID {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	slice := ChallengeThemeSlice{&local}
	if err = local.L.LoadUser(ctx, tx, false, (*[]*ChallengeTheme)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.User == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.User = nil
	if err = local.L.LoadUser(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.User == nil {
		t.Error("struct should have been eager loaded")
	}
}

func testChallengeThemeToOneSetOpUserUsingUser(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a ChallengeTheme
	var b, c User

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, challengeThemeDBTypes, false, strmangle.SetComplement(challengeThemePrimaryKeyColumns, challengeThemeColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*User{&b, &c} {
		err = a.SetUser(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.User != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.ChallengeThemes[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.UserID != x.ID {
			t.Error("foreign key was wrong value", a.UserID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.UserID))
		reflect.Indirect(reflect.ValueOf(&a.UserID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.UserID != x.ID {
			t.Error("foreign key was wrong value", a.UserID, x.ID)
		}
	}
}

func testChallengeThemesReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ChallengeTheme{}
	if err = randomize.Struct(seed, o, challengeThemeDBTypes, true, challengeThemeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ChallengeTheme struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testChallengeThemesReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ChallengeTheme{}
	if err = randomize.Struct(seed, o, challengeThemeDBTypes, true, challengeThemeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ChallengeTheme struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := ChallengeThemeSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testChallengeThemesSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &ChallengeTheme{}
	if err = randomize.Struct(seed, o, challengeThemeDBTypes, true, challengeThemeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ChallengeTheme struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := ChallengeThemes().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	challengeThemeDBTypes = map[string]string{`ID`: `int`, `Title`: `text`, `Description`: `text`, `UserID`: `int`, `Recordable`: `tinyint`, `IsInt`: `tinyint`, `Unit`: `varchar`, `RankingType`: `tinyint`, `CreatedAt`: `datetime`}
	_                     = bytes.MinRead
)

func testChallengeThemesUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(challengeThemePrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(challengeThemeAllColumns) == len(challengeThemePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &ChallengeTheme{}
	if err = randomize.Struct(seed, o, challengeThemeDBTypes, true, challengeThemeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ChallengeTheme struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := ChallengeThemes().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, challengeThemeDBTypes, true, challengeThemePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize ChallengeTheme struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testChallengeThemesSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(challengeThemeAllColumns) == len(challengeThemePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &ChallengeTheme{}
	if err = randomize.Struct(seed, o, challengeThemeDBTypes, true, challengeThemeColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize ChallengeTheme struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := ChallengeThemes().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, challengeThemeDBTypes, true, challengeThemePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize ChallengeTheme struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(challengeThemeAllColumns, challengeThemePrimaryKeyColumns) {
		fields = challengeThemeAllColumns
	} else {
		fields = strmangle.SetComplement(
			challengeThemeAllColumns,
			challengeThemePrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := ChallengeThemeSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testChallengeThemesUpsert(t *testing.T) {
	t.Parallel()

	if len(challengeThemeAllColumns) == len(challengeThemePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}
	if len(mySQLChallengeThemeUniqueColumns) == 0 {
		t.Skip("Skipping table with no unique columns to conflict on")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := ChallengeTheme{}
	if err = randomize.Struct(seed, &o, challengeThemeDBTypes, false); err != nil {
		t.Errorf("Unable to randomize ChallengeTheme struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert ChallengeTheme: %s", err)
	}

	count, err := ChallengeThemes().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, challengeThemeDBTypes, false, challengeThemePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize ChallengeTheme struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert ChallengeTheme: %s", err)
	}

	count, err = ChallengeThemes().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
