// Code generated by SQLBoiler 3.6.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package model

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("ChallengeRecords", testChallengeRecordsUpsert)

	t.Run("ChallengeThemes", testChallengeThemesUpsert)

	t.Run("Favorites", testFavoritesUpsert)

	t.Run("Tags", testTagsUpsert)

	t.Run("ThemeTagRelations", testThemeTagRelationsUpsert)

	t.Run("Users", testUsersUpsert)
}
